import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Statement;

public class UserInNeed extends UserClass {
	public UserInNeed(int id, String name,String surname,Date birth_date,int phone,String email,String location) {
		super(id,name, surname, birth_date,phone, email,location);
	}
	
	
	
	 public String userInNeedToString(UserInNeed userInNeed) {
	        return "INSERT INTO UserInNeed (idUserInNeed, name, surname, birth_date, phone, email, location) VALUES (" +
	               "'" + userInNeed.get_id() + "', " +
	               "'" + userInNeed.get_name() + "', " +
	               "'" + userInNeed.get_surname() + "', " +
	               "'" + userInNeed.get_birth_date() + "', " +
	               "'" + userInNeed.get_phone() + "', " +
	               "'" + userInNeed.get_email() + "', " +
	               "'" + userInNeed.getLocation() + "')";
	    }

	    // Method to add a UserInNeed to the database
	    public void addUserInNeed(UserInNeed userInNeed, Connection conn) throws SQLException {
	        Statement stmt = conn.createStatement();

	        // Execute the SQL statement generated by userInNeedToString
	        stmt.executeUpdate(userInNeedToString(userInNeed));
	        
	    }
}
